### ISSUE TITLE
Save image path in event

### ISSUE THREAD

**Issue by runningman84** [snowzach/hassdoods#1]
In order to send images via telegram it would be nice to have the saved images in an array attached to the detection event. This would allow us to use a filename with a datetime attached.

Storing just the latest image can cause problems because their might be a delay between the detection and the actual image sending.

**Comment by runningman84** [comment]
Hmm maybe this could be implemented in a generic way:
https://community.home-assistant.io/t/image-saved-event/136094

**Comment by snowzach** [comment]
The downside of putting it in an event is that it would probably get persisted in the database. It would probably be better to have the image filenames be part of the event/state. You could save the files with a timestamp and ensure they remain unique and then clean them up later. Once the component actually gets accepted we can work on adding features. I don't want to start the review process over again.

**Comment by snowzach** [comment]
Closing this in favor of #3
