### ISSUE TITLE
Allow changing the bounding box color

### ISSUE THREAD

**Issue by santibur06** [snowzach/hassdoods#7]
Sometimes images are too bright and the yellow letters with the detected object name and confidence can't really be read. Is there a way to change the color?

**Comment by snowzach** [comment]
Unfortunately not right now. I'm not really working on this one anymore. I am working on the next version DOODS2. I will likely add a way to change the color in that one.

**Comment by santibur06** [comment]
I actually meant to open this ticket at the doods2 repo. I'm using doods2 in docker, working perfectly so far. Yeah, changing the bounding boxes color and maybe font size would be very useful. Also, is there a way this info could be stored to the image metadata? This is really useful for debuging and tuning the detector.

Thanks!

**Comment by snowzach** [comment]
Have you tried using the new web interface? It's good for realtime tuning but not so much for after the fact. I might be able to add exim metadata if you think that might be useful. It doesn't look too hard. If I can just add the detection info Json to the image I could possibly do that.

**Comment by santibur06** [comment]
I hadn't tried the web interface, pretty useful tool, thank you! re: metadata, I'm taking pictures every time the detector finds a person, sometimes it detects something else as a person and I can't really read the confidence it had for that object cause it's ether cut out of the photo or the yellow text isn't readable in a bright background. Having that info stored in the photo would be pretty useful. thanks!

**Comment by snowzach** [comment]
I couldn't figure out how to write exif data to the image. cv2 doesn't seem to support it. DOODS2 now fully supports setting the box and font colors. If you find some useful defaults that work better than mine (which wouldn't be hard, I just picked random colos) please feel free to pass them on. https://github.com/snowzach/doods2/commit/f6e2cba90657faa7bc99cde4056977c558a63a79

**Comment by santibur06** [comment]
awesome, I'll test it out! by the way, the web ui works great, I'll open another feedback ticket to comment on something related to the detection areas which would be quite useful to be able to define using the UI and obtain the yaml to then use
